define([], function() {
  return {
    "PropertyPaneDescription": "Point each tab at a SharePoint list and tell the dashboard which internal field names to use.",
    "GeneralGroupName": "General",
    "QuotationGroupName": "Quotation pipeline tab",
    "LeadsGroupName": "Sales Lead tab",
    "ActivityGroupName": "Activity tab",
    "ProjectsGroupName": "Projects tab",
    "TitleFieldLabel": "Dashboard title",
    "DefaultDashboardTitle": "Manager Dashboard",
    "ItemLimitFieldLabel": "Items to load per list",
    "ProbabilityThresholdFieldLabel": "High probability threshold (%)",
    "ListTitleFieldLabel": "List title",
    "ColumnsFieldLabel": "Columns",
    "ColumnsFieldDescription": "Comma separated internal names. Leave empty to show the first few columns automatically. Use the Fields button on the tab to look the internal names up.",
    "DateFieldLabel": "Due date field",
    "DateFieldDescription": "Internal name of the date field behind the Overdue and Due in 7 days tiles.",
    "StatusFieldLabel": "Status field",
    "StatusFieldDescription": "Internal name of the choice field behind the status filter and the Open tile.",
    "QuotationStatusFieldDescription": "Internal name of the 22-value status choice column. The pipeline order comes from src/statuses.ts.",
    "AmountFieldLabel": "Amount field",
    "RemarksFieldLabel": "Remarks field",
    "OptionalFieldDescription": "Internal name. Leave empty to hide this field from the grid and the edit panel.",
    "LeadLinkFieldLabel": "Sales Lead link field",
    "LeadLinkFieldDescription": "Internal name of the lookup on Quotation pointing at Sales Lead. Leave empty to turn the lead sync off.",
    "LeadStageFieldLabel": "Lead stage field",
    "LeadStageFieldDescription": "Internal name of the stage lookup on the Sales Lead list. A renamed column keeps its original internal name.",
    "ProbabilityFieldLabel": "Probability field",
    "ProbabilityFieldDescription": "Internal name of the numeric field behind the high probability tile.",
    "AppLocalEnvironmentSharePoint": "Running locally as a SharePoint web part",
    "AppLocalEnvironmentTeams": "Running locally as a Microsoft Teams app",
    "AppLocalEnvironmentOffice": "Running locally in office.com",
    "AppLocalEnvironmentOutlook": "Running locally in Outlook",
    "AppSharePointEnvironment": "SharePoint",
    "AppTeamsTabEnvironment": "Microsoft Teams",
    "AppOfficeEnvironment": "office.com",
    "AppOutlookEnvironment": "Outlook",
    "UnknownEnvironment": "Unknown environment"
  }
});
